language: node_js

node_js:
  - "6"
  
script:
  - "npm install"

after_success:
- bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
#- bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="https://hubeval32.blackducksoftware.com" --blackduck.hub.username="ntu" --blackduck.hub.password="ntu@2018" --blackduck.hub.trust.cert=true --detect.policy.check=true
